# Generated by Django 3.0.3 on 2020-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200822_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcustomer',
            name='ship',
            field=models.TextField(blank=True, null=True),
        ),
    ]
