# Generated by Django 3.0.3 on 2020-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactcustomer_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcustomer',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactmanufacturer',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactseller',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
