# Generated by Django 3.0.3 on 2020-09-04 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200904_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcustomer',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='contactmanufacturer',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='contactseller',
            name='is_done',
        ),
        migrations.AddField(
            model_name='contactcustomer',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactmanufacturer',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactseller',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
