# Generated by Django 3.0.3 on 2020-09-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_all_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactcustomer',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
