# Generated by Django 3.0.3 on 2020-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200905_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanufacturer',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactseller',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
