# Generated by Django 3.0.3 on 2020-09-08 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0009_auto_20200905_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All',
            new_name='AllCustomer',
        ),
    ]
