# Generated by Django 3.0.3 on 2020-09-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0010_auto_20200908_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default=True, null=True)),
                ('last_name', models.TextField(default=True, null=True)),
                ('number', models.TextField(default=True, null=True)),
                ('email', models.TextField(default=True, null=True)),
                ('username', models.TextField(default=True, null=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.TextField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
