# Generated by Django 3.0.3 on 2020-09-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_allmanufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanufacturer',
            name='company_name',
            field=models.TextField(null=True),
        ),
    ]
