# Generated by Django 3.0.3 on 2020-09-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_allmanufacturer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmanufacturer',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contactmanufacturer',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
