# Generated by Django 3.0.3 on 2020-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20200909_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmanufacturer',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmanufacturer',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
