# Generated by Django 3.0.3 on 2020-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20200909_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmanufacturer',
            name='checkvalue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmanufacturer',
            name='checkvalue',
            field=models.TextField(null=True),
        ),
    ]
