# Generated by Django 3.0.3 on 2020-09-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20200910_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmanufacturer',
            name='resources',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmanufacturer',
            name='resources',
            field=models.TextField(null=True),
        ),
    ]
