# Generated by Django 3.0.3 on 2020-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20200910_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmanufacturer',
            name='checkvalue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allmanufacturer',
            name='resources',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allmanufacturer',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmanufacturer',
            name='checkvalue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmanufacturer',
            name='resources',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmanufacturer',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
