# Generated by Django 3.0.3 on 2020-09-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20200911_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRfqDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('process', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('adddetails', models.TextField(blank=True, null=True)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('nearestloc', models.IntegerField(blank=True, null=True)),
                ('leadtime', models.IntegerField(blank=True, null=True)),
                ('pricing', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.AllManufacturer')),
            ],
        ),
    ]
