# Generated by Django 3.0.3 on 2020-09-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20200913_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrfqdetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.AllManufacturer'),
        ),
    ]
