# Generated by Django 3.0.3 on 2020-09-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_quotesrecieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
