# Generated by Django 3.0.3 on 2020-09-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_quotesrecieved_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotesrecieved',
            old_name='name',
            new_name='uname',
        ),
    ]
