# Generated by Django 3.0.3 on 2020-09-16 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_auto_20200916_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
