# Generated by Django 3.0.3 on 2020-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_quotesrecieved_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
