# Generated by Django 3.0.3 on 2020-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_quotesrecieved_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='reject',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
