# Generated by Django 3.0.3 on 2020-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_auto_20200916_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesrecieved',
            name='reject',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
    ]
