# Generated by Django 3.0.3 on 2020-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0033_auto_20200916_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='fromcustomer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
