# Generated by Django 3.0.3 on 2020-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_quotesrecieved_fromcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='statusquote',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
