# Generated by Django 3.0.3 on 2020-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0035_quotesrecieved_statusquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesrecieved',
            name='statusquote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
