# Generated by Django 3.0.3 on 2020-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0038_customerrfqdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrfqdetails',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
