# Generated by Django 3.0.3 on 2020-09-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0040_customerrfqdetails_reject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrfqdetails',
            old_name='reject',
            new_name='rejecter',
        ),
    ]
