# Generated by Django 3.0.3 on 2020-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0043_auto_20200925_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='complaintmade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
