# Generated by Django 3.0.3 on 2020-09-26 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0046_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
