# Generated by Django 3.0.3 on 2020-09-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0047_blog_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
