# Generated by Django 3.0.3 on 2020-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0048_blog_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
