# Generated by Django 3.0.3 on 2020-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0049_auto_20200927_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
