# Generated by Django 3.0.3 on 2020-11-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0051_auto_20201112_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesrecieved',
            name='complaintitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
