# Generated by Django 3.1.5 on 2021-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0053_quotesrecieved_complaintchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
