# Generated by Django 3.0.3 on 2020-09-01 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('quality', models.IntegerField(null=True)),
                ('nearestloc', models.IntegerField(null=True)),
                ('leadtime', models.IntegerField(null=True)),
                ('pricing', models.IntegerField(null=True)),
                ('adddetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
