# Generated by Django 3.0.3 on 2020-09-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='adddetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='leadtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='nearestloc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='pricing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
