# Generated by Django 3.0.3 on 2020-09-01 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_auto_20200901_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
