# Generated by Django 3.0.3 on 2020-09-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_auto_20200902_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
