# Generated by Django 3.0.3 on 2020-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0007_rfq_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
