# Generated by Django 3.0.3 on 2020-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0008_auto_20200902_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
