# Generated by Django 3.0.3 on 2020-09-11 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0009_auto_20200902_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='listing_id',
            field=models.IntegerField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
