# Generated by Django 3.0.3 on 2020-09-11 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0010_rfq_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='listing_id',
            field=models.IntegerField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
