# Generated by Django 3.0.3 on 2020-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0013_remove_rfq_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
